Repository CMPUT301F22T18/SnackNTrack, pull requests merged in 2022-11, with the labels that each got.

#65 Issues/33: Class: Storage
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientBBDComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientCategoryComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientDescriptionComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientLocationComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/Storage.java
Labels: half-way checkpoint

#75 Issues/74
  app/src/main/java/com/cmput301f22t18/snackntrack/Recipe.java
Labels: Urgent

#66 Issues/28: Storage: Display a list of Ingredients
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cmput301f22t18/snackntrack/RecipeListAdapter.java
  app/src/main/java/com/cmput301f22t18/snackntrack/Storage.java
  app/src/main/java/com/cmput301f22t18/snackntrack/StorageActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/StorageAdapter.java
  app/src/main/res/drawable/category_label.xml
  app/src/main/res/drawable/location_label.xml
  app/src/main/res/layout/activity_storage.xml
  app/src/main/res/layout/storage_row_item.xml
  app/src/main/res/values/strings.xml
Labels: half-way checkpoint

#70 Issues/57: Test Class: Ingredients
  app/src/androidTest/java/com/cmput301f22t18/snackntrack/ExampleInstrumentedTest.java
  app/src/test/java/com/cmput301f22t18/snackntrack/ExampleUnitTest.java
  app/src/test/java/com/cmput301f22t18/snackntrack/IngredientTest.java
Labels: half-way checkpoint

#71 Issues/60: Test Class: Storage
  app/build.gradle
  app/src/main/java/com/cmput301f22t18/snackntrack/Storage.java
  app/src/test/java/com/cmput301f22t18/snackntrack/StorageTest.java
Labels: half-way checkpoint

#96 Issues/84: Authentication using Firebase UI and More
  app/build.gradle
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cmput301f22t18/snackntrack/AddEditIngredientFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/AddIngredientToRecipeFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/AddRecipeFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/DBController.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientBBDComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientCategoryComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientDescriptionComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/IngredientLocationComparator.java
  app/src/main/java/com/cmput301f22t18/snackntrack/MainActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/MainMenuActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/RecipeListActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/RecipeListAdapter.java
  app/src/main/java/com/cmput301f22t18/snackntrack/StorageActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/StorageAdapter.java
  app/src/main/java/com/cmput301f22t18/snackntrack/controllers/DBController.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/AppUser.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/Ingredient.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/Recipe.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/RecipeList.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/Storage.java
  app/src/main/res/drawable/category_label.xml
  app/src/main/res/drawable/custom_image_button.xml
  app/src/main/res/drawable/location_label.xml
  app/src/main/res/layout/activity_main.xml
  app/src/main/res/values-night/themes.xml
  app/src/main/res/values/colors.xml
  app/src/main/res/values/strings.xml
  app/src/main/res/values/themes.xml
  app/src/test/java/com/cmput301f22t18/snackntrack/IngredientTest.java
  app/src/test/java/com/cmput301f22t18/snackntrack/RecipeListTest.java
  app/src/test/java/com/cmput301f22t18/snackntrack/RecipeTest.java
  app/src/test/java/com/cmput301f22t18/snackntrack/StorageTest.java
  build.gradle
Labels: Risk Level: High

#114 Issues/41: Edit a Recipe
  app/src/main/AndroidManifest.xml
  app/src/main/java/com/cmput301f22t18/snackntrack/AddEditRecipeActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/AddIngredientToRecipeFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/AddRecipeFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/RecipeIngredientAdapter.java
  app/src/main/java/com/cmput301f22t18/snackntrack/RecipeListFragment.java
  app/src/main/java/com/cmput301f22t18/snackntrack/ViewRecipeActivity.java
  app/src/main/java/com/cmput301f22t18/snackntrack/models/Recipe.java
  app/src/main/res/drawable/ic_baseline_image_24.xml
  app/src/main/res/drawable/ic_baseline_timer_24.xml
  app/src/main/res/layout/activity_add_edit_recipe.xml
  app/src/main/res/layout/content_recipe_ingredient.xml
  app/src/main/res/layout/fragment_add_edit_recipe.xml
  app/src/main/res/layout/fragment_add_ingredient_to_recipe.xml
  app/src/main/res/values/strings.xml
Labels: Risk Level: High
